site_name: SIH Bioinformatics Training
repo_url: https://github.com/Sydney-Informatics-Hub/bioinformatics-training
repo_name: Sydney-Informatics-Hub/bioinformatics-training

nav:
  - Home: index.md 
  - Learners: learners.md 
  - Trainers: trainers.md 

theme:
  name: material
  logo: assets/usyd-logo.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.external.links
  palette:
    - scheme: default
      primary: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search
  - table-reader:
      data_path: "docs"
      allow_missing_files: false
      select_readers:
        - read_csv
        - read_table
  - privacy:
      external_links: true
      external_links_attr_map:
        target: _blank
        rel: noopener noreferrer
      links_attr_map:
        target: _blank
        rel: noopener noreferrer
      external_links_noopener: true

extra_css:
  - extra.css

extra_javascript:
  - assets/js/external-links.js

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      preserve_tabs: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - pymdownx.superfences

extra:
  analytics:
    provider: google
    property: G-TNWWV3HK57
